package dyd.usizo.rest;

import dyd.usizo.accessingdatamysql.*;
import dyd.usizo.models.Need;
import dyd.usizo.models.Product;
import dyd.usizo.models.ShoppingList;
import dyd.usizo.models.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.ArrayList;
import java.util.List;

@RestController
public class ShoppingListApi {

    @Autowired // This means to get the bean called shoppingListRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ShoppingListRepository shoppingListRepository;
    @Autowired
    private UserRepository userRepository;
    @Autowired
    private ProductRepository productRepository;
    @Autowired
    private NeedRepository needRepository;
    @Autowired
    private RoleRepository roleRepository;

    @GetMapping("/api/shoppingList")
    public ShoppingList getShoppingList(@RequestParam(value = "action", defaultValue = "find") String action, @RequestParam(value = "id", defaultValue = "1") int id) {
        if(action.equals("find"))return shoppingListRepository.findById(id).get();
        else {
            shoppingListRepository.delete(shoppingListRepository.findById(id).get());
            return null;
        }
    }

    @GetMapping("/api/shoppingLists")
    public Iterable<ShoppingList> getShoppingLists() {
        if (!shoppingListRepository.findAll().iterator().hasNext()){
            List<ShoppingList> sl = new ArrayList<>();
            ShoppingList l = new ShoppingList(userRepository.save(new User("Dylan", "" , roleRepository.findById(2).get())));
            Product p = productRepository.save(new Product("Javel", "", "Produit ménager"));
            Product p2 = productRepository.save(new Product("Balai", "", "Ménage"));
            Need n = needRepository.save(new Need(p,5));
            Need n2 = needRepository.save(new Need(p2,1));
            l.getNeedList().add(n);
            l.getNeedList().add(n2);
            sl.add(l);
            shoppingListRepository.saveAll(sl);
        }
        return shoppingListRepository.findAll();
    }

}